name: Playwright Tests
on:
  push:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: pnpm 설정
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.1
          cache: 'pnpm'

      - name: 의존성 설치
        run: pnpm install

      - name: Playwright 설치
        run: pnpm playwright install --with-deps

      - name: 개발 서버 시작
        run: pnpm dev & npx wait-on http://localhost:5173
        env:
          CI: true

      - name: Playwright 실행
        run: pnpm test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
